### ISSUE TITLE
demo no extensions found

### ISSUE THREAD

**Issue by ghanIn** [pf4j/pf4j-wicket#15]
![image](https://user-images.githubusercontent.com/15894443/50628807-f8709580-0f7c-11e9-97a8-91b7136657b9.png)
![image](https://user-images.githubusercontent.com/15894443/50628822-10481980-0f7d-11e9-9911-c4d8a0c41ce4.png)

run-demo.bat work well but No extensions found

**Comment by decebals** [comment]
I need more information. Please read https://pf4j.org/doc/troubleshooting.html

**Comment by decebals** [comment]
Closed due to lack of information. Please reopen if you need help.
